### ISSUE TITLE
multiple nightwatch env's kill browsers early

### ISSUE THREAD

**Issue by peter-mouland** [bermi/sauce-connect-launcher#100]
Hi,

When using sauce-connect-launcher, running `nightwatch -e chromemac,ie11` only one environment actually runs.  You can see from the output below that an environment finishes straight away.

Have you seen this before?

Thanks,

```
Started child process for: chromemac environment 
Started child process for: ie11 environment 

  >> ie11 environment finished.  

```

In my nightwatch.conf.js I have set some before/after globals in order to start the launcher:

```js
  settings.test_settings.default.globals = {
    TARGET_PATH: target,
    before: (done) => {
      Promise.resolve()
        .then(() => (!settings.selenium.start_process)
          ? openSauce()
          : Promise.resolve()
        )
        .then(done)
        .catch(catchError);
    },
    after: function (done) {
      Promise.resolve()
        .then(() => (!settings.selenium.start_process)
          ? closeSauce()
          : Promise.resolve()
        )
        .then(done)
        .then(() => process.exit(0))
        .catch(catchError);
    }
  };
```

and the open/close sauce functions are:

```js
let sauce;
const closeSauce = () => new Promise((resolve, reject) => {
  sauce.close(resolve);
});

const openSauce = () => new Promise((resolve, reject) => {
  sauceConnectLauncher(sauceConfig, ((err, process) => {
    console.log("Started Sauce Connect Process");
    sauce = process;
    err && reject(err);
    !err && resolve(process);
  }))
});
const catchError = (e) => console.log(`e`, e);
```

**Comment by peter-mouland** [comment]
i've updated the code for the connection. i theory it should be good to go (aweful use of globals to check if connection has already been made)

```js
const sauceConnectLauncher = require('sauce-connect-launcher');
const sauceConfig = require('./test/config/sauceLabsConnect');
let sauce;
let launcher;


const closeSauce = () => new Promise((resolve, reject) => {
  try {
    sauce.close(resolve);
  } catch(e){
    console.log(e)
  }
});

const openSauce = (cb) => {
  if (!launcher){
    launcher = new Promise((resolve, reject) => {
      sauceConnectLauncher(sauceConfig, ((err, process) => {
          console.log("Started Sauce Connect Process");
          sauce = process;
          err && reject(err);
          !err && resolve(process);
        }));
    });
  }
  return launcher.then(() => {
    return cb();
  });
};

module.exports = {
  closeSauce, openSauce
};
```


**but** i guess nightwatch opens the browser envs in new processes which mean the code above never works.

have you an idea how to get this working in the `before` task of nighwatch?

**Comment by johanneswuerbach** [comment]
Not really and I think a better place for this issue might be https://github.com/nightwatchjs/nightwatch/issues as they should be able to help you better.

**Comment by peter-mouland** [comment]
Is there a way of detecting if this launcher has connected?
either through node api or command line?

**Comment by johanneswuerbach** [comment]
Yes, its connected once you provided callback is called. You can also see currently running tunnels here https://saucelabs.com/beta/tunnels

**Comment by peter-mouland** [comment]
thanks for the link, but I'm trying to set this up programatically. i.e. `npm run tests` which will automatically start my app, then connect to sauceLabs, then run tests.

**Comment by johanneswuerbach** [comment]
Still no 100%-sure what you are trying to achieve, but can check whether a sauce-connect tunnel is running using the `pidfile` option: https://wiki.saucelabs.com/pages/viewpage.action?pageId=48365781

**Comment by jstockwin** [comment]
@peter-mouland I'm currently working on a similar setup to you over at KeystoneJS. 
What you need to do is connect to saucelabs outside of all of the Nightwatch stuff.

You can start Nightwatch programmatically using their CLI runner, so you just need to start sauce connect, then run the Nightwatch CLI runner, and then once that's finished close sauce connect.

**Comment by peter-mouland** [comment]
closing issue as I can't add any more info... or remember the details!

**Comment by ShhDhruvin** [comment]
Hi,
I am getting below error after adding above mentioned things in nightwatch.config.js:

Started Sauce Connect Process
e Error: Could not start Sauce Connect. Exit code 1 signal: null
    at ChildProcess.<anonymous> (C:\Mint\Repositories\nightwatch1.0.18-saucelabTesting\node_modules\sauce-connect-launcher\lib\sauce-connect-launcher.js:559:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
   done() callback timeout of 10000ms was reached while executing "before". Make sure to call the done() callback when the operation finishes.

What is the reason behind this?
