### ISSUE TITLE
RFC: Release 1.0

### ISSUE THREAD

**Issue by johanneswuerbach** [bermi/sauce-connect-launcher#102]
Following http://semver.org/#how-do-i-know-when-to-release-100 I would propose to bump the next version to 1.0 and allow package consumers to easier differentiate between breaking changes / new features or patches. Currently every 0.x release can contain breaking changes according to semver and package consumers can't just use `^0.x` to get new features / sc versions.

Before cutting 1.0 the following should be done (from my point of view):
- [x] Merge https://github.com/bermi/sauce-connect-launcher/pull/101 
- [x] Merge https://github.com/bermi/sauce-connect-launcher/pull/99
- [x] Merge https://github.com/bermi/sauce-connect-launcher/pull/97
- [x] Remove support for Node 0.10 & 0.12 as both are already EOL or will soon be https://github.com/nodejs/LTS

WDYT? @bermi @jlipps @sebv @aearly @jonahss

**Comment by jlipps** [comment]
@johanneswuerbach that looks like a solid plan. I think Node support should be moved to current LTS i.e. 6.9

**Comment by johanneswuerbach** [comment]
I wouldn't remove Node 4, as it is actively maintained until 2018-04-01, still used a lot and 6 just entered the LTS phase.

**Comment by jlipps** [comment]
Sticking with Node 4 is also OK
