### ISSUE TITLE
Corrupted downloads

### ISSUE THREAD

**Issue by ballwood** [bermi/sauce-connect-launcher#122]
Hi,

Using the latest sauce connect launcher. On OSX it seems when I set an authenticated proxy (http://username:password@proxy:8080, not https) I'm getting a corrupted download. I've tried opening the file up manually and it gives me the below error. Anyone else have this issue?

  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

**Comment by ballwood** [comment]
Closed

**Comment by johanneswuerbach** [comment]
Were you able to identify the issue?

**Comment by ballwood** [comment]
Not entirely sure what it was...something node related as the proxy download worked on chrome correctly. It looked like it was chopping off the last 30kb of the download. Sorted it out by putting together my own package based off Chrome Driver.
