### ISSUE TITLE
Publish 1.2.1

### ISSUE THREAD

**Issue by xaka** [bermi/sauce-connect-launcher#124]
It seems 1.2.1 never got published to npm :( would be nice to have it there as it includes important fix for tunnel ID. 

Thanks!

---

<img width="226" alt="screen shot 2017-04-12 at 11 01 06 pm" src="https://cloud.githubusercontent.com/assets/504813/24992047/ed2417e6-1fd3-11e7-8c25-2c74a4c9bf69.png">

**Comment by johanneswuerbach** [comment]
Sorry, published.
