### ISSUE TITLE
Could not start Sauce Connect

### ISSUE THREAD

**Issue by parris** [bermi/sauce-connect-launcher#137]
Locally (on my mac) this library works totally fine. However, in jenkins (running in CentOS) the connection to sauce fails without any details really. We should be getting very verbose messages (I set all those config variables to true), but I don't see much.

Here is the log:

```
$ wdio webdriver.config.js

/workspace/packages/endtoend/node_modules/webdriverio/build/lib/cli.js:446
                throw e;
                ^

Error: Could not start Sauce Connect. Exit code 1 signal: null
    at ChildProcess.<anonymous> (/workspace/packages/endtoend/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:559:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
error Command failed with exit code 1.
```

Checking that line of code doesn't really reveal too much about the failure. Any ideas about where/how to start debugging this?

**Comment by parris** [comment]
Nevermind, sometimes the problem is the most obvious thing: check that your environment variables are getting passed in properly 🤦‍♂️ . If you're in jenkins and you have a docker type setup your environment variables are likely not making to your test runner.

**Comment by mbracker** [comment]
@parris do you recall which env vars you needed to ensure were passed down?
