### ISSUE TITLE
Use drivers from local resource instead of internet download

### ISSUE THREAD

**Issue by sebs** [bermi/sauce-connect-launcher#139]
Sorry, might be an issue in rural Zones of some zones (deep siberia, north pole, mars) and Germany where a install can take a long time. Can I tell sauce connetc launcher to use drivers from a local folder? 

Preferably with a environment variable. I just waited 25 min. for the driver to dl in a train.

**Comment by johanneswuerbach** [comment]
Yes, you can define a path to an executable using the `exe` option, which skips the download.

https://github.com/bermi/sauce-connect-launcher#advanced-usage
