### ISSUE TITLE
Backward-compatibility is broken in release 1.2.5

### ISSUE THREAD

**Issue by vgrigoruk** [bermi/sauce-connect-launcher#143]
See my comment here: https://github.com/bermi/sauce-connect-launcher/pull/142#issuecomment-491270276

Related PRs: https://github.com/bermi/sauce-connect-launcher/pull/140, https://github.com/bermi/sauce-connect-launcher/pull/142

**Comment by johanneswuerbach** [comment]
Sorry about the breakage, fix released as `v1.2.7`
