### ISSUE TITLE
Stack updata and extending options

### ISSUE THREAD

**Issue by valishah** [bermi/sauce-connect-launcher#145]
Hello @bermi, 
 Hope this repo is allowing active contributions. I would like to help in extending the capabilities and upgrading the tech stack. Please do let me know if it's fine. 

**Proposals**
 - ES6, Jest, Release automation
 - Sauce Connect: Multi tunnel execution. Flexibility of consuming API's etc. 

Looking forward to hearing form you.

**Comment by johanneswuerbach** [comment]
Sure, happy to review & merge pull requests :-)

**Comment by bermi** [comment]
@valishah that would be awesome.

I suggest connecting with @johanneswuerbach before making significant refactorings since he's been merging most PR's for the last few years. I  also recommend keeping the PR's scoped to a single theme to make it easier to review and discuss.

**Comment by valishah** [comment]
Thanks @johanneswuerbach  & @bermi
