### ISSUE TITLE
Please update https-proxy-agent dependency to 5.x.x

### ISSUE THREAD

**Issue by FrittenToni** [bermi/sauce-connect-launcher#155]
Hi @bermi, @johanneswuerbach,

first of all thanks for the great tool you provide for the community. While using it I unfortunately discovered an issue with Node >=10 and https-proxy-agent library. 

The issue leads to a problem where all requests in my code are suddenly routed through a proxy even though I have never specified one. All my requests are getting rejected with error: connect ECONNREFUSED 127.0.0.1:443

It turns out that old versions of https-proxy-agent library are patching NodeJS https core modules and this doesn't seem to work properly with newer NodeJS versions as described [here](https://github.com/sindresorhus/got/issues/951).

 I can confirm that commenting out the HttpsProxyAgent line [here](https://github.com/bermi/sauce-connect-launcher/blob/master/lib/sauce-connect-launcher.js#L11) fixes the problem for me.

For this reason I propose to update https-proxy-agent library to version 5.x.x. as the patching logic [got removed ](https://github.com/TooTallNate/node-agent-base/releases/tag/5.0.0)with that version.

Regards,
Fritte

**Comment by johanneswuerbach** [comment]
@FrittenToni , I would happily review and merge a pull request :-)

**Comment by johanneswuerbach** [comment]
Fixed by https://github.com/bermi/sauce-connect-launcher/pull/156

**Comment by FrittenToni** [comment]
@johanneswuerbach Thanks for merging this so quickly. Everything is running fine now 👍
