### ISSUE TITLE
[question] Checksum of the downloaded archive doesn't match 

### ISSUE THREAD

**Issue by vire** [bermi/sauce-connect-launcher#159]
I'm a user of of [testcafe-browser-provider-saucelabs](https://github.com/DevExpress/testcafe-browser-provider-saucelabs) that has `sauce-connect-launcher@1.3.1` as dependency and today it started throwing following error (locally and on CI)

![image](https://user-images.githubusercontent.com/4021908/90015280-a93a2d00-dca8-11ea-993a-099768aad78c.png)

Upgrading to `1.3.2` did not resolve the problem

Question: is it possible to force a re-download

EDIT: 

content of `./node_modules/saucelabs-connector/node_modules/sauce-connect-launcher/sc`

```

    "Sauce Connect": {
        "download_url": "https://wiki.saucelabs.com/display/DOCS/Setting+Up+Sauce+Connect", 
        "linux": {
            "build": 5183, 
            "download_url": "https://saucelabs.com/downloads/sc-4.6.2-linux.tar.gz", 
            "sha1": "7b7f35433af9c3380758e048894d7b9aecf3754e"
        }, 
        "linux32": {
            "build": 5183, 
            "download_url": "https://saucelabs.com/downloads/sc-4.6.2-linux32.tar.gz", 
            "sha1": "ce96d8543f013e0112a678aa9980e95331421cb1"
        }, 
        "osx": {
            "build": 5183, 
            "download_url": "https://saucelabs.com/downloads/sc-4.6.2-osx.zip", 
            "sha1": "51c6c152eb54c20d8969a9d5917ebecc3ac868e1"
        }, 
        "version": "4.6.2", 
        "win32": {
            "build": 5183, 
            "download_url": "https://saucelabs.com/downloads/sc-4.6.2-win32.zip", 
            "sha1": "4b8955c806998226ed41592cbe45c929c0f88a87"
        }
    }, 
    "Sauce Connect 2": {
        "download_url": "https://docs.saucelabs.com/reference/sauce-connect/", 
        "version": "4.3.13-r999"
    }
}
```

**Comment by FrittenToni** [comment]
We faced the same issue today. A workaround is to reference a fixed sauce connect version (e.g. connectVersion: '4.6.2') as in that case checksum check is disabled (check README or the code [here](https://github.com/bermi/sauce-connect-launcher/blob/d8336fb8f8829dbbb0a94d405acbdcdbf6668433/lib/sauce-connect-launcher.js#L310)).

This package seems to use a saucelabs versions endpoint, e.g. https://eu-central-1.saucelabs.com/versions.json for downloading sauce connect proxy binary and retrieving the corresponding checksum. After the file has been downloaded a local checksum is generated and compared to the one retrieved from versions endpoint. 

Suddenly this check is failing as the locally generated sha1 doesn't match the one retrieved from the versions.json endpoint. I tried downloading sc-4.6.2-linux.tar.gz and generated a checksum locally by using `shasum sc-4.6.2-linux.tar.gz` command and end up at the same result as the sauce connect launcher. The downloaded archive doesn't match the expected sha1. Therefore, it could be possible that the current issue is on saucelabs side.

**Comment by vire** [comment]
@FrittenToni at my machine the newly downloaded `sc-4.6.2-osx.zip` looks tampered :suspect: because I have an older version

![image](https://user-images.githubusercontent.com/4021908/90019762-25d00a00-dcaf-11ea-92a6-b95f8da24844.png)

**Comment by FrittenToni** [comment]
I've reported the issue to saucelabs. They fixed it and everything should work fine again when you want to use 'latest' as connectVersion. @vire Not sure why you get two different checksums though. Maybe saucelabs just releases new binaries under the same version and this leads to different checksums.
