### ISSUE TITLE
"Invalid or unsupported zip format. No END header found" downloading OSX zip file

### ISSUE THREAD

**Issue by kaldrenon** [bermi/sauce-connect-launcher#45]
Downloading https://saucelabs.com/downloads/sc-4.3.5-osx.zip (2.92MB)
    Unzipping /app_root/node_modules/web-component-tester/node_modules/sauce-connect-launcher/sc/sc-4.3.5-osx.zip

    Invalid or unsupported zip format. No END header found

I am getting this error ~80% of the time when I run `npm install` on a project with `sauce-connect-launcher` in its dependencies. Occasionally, the download works, but it usually doesn't. when it doesn't, my whole `npm install` fails.

Is this just an issue with that zip file, or is there another factor? What needs to be done to make the install stable?

**Comment by aearly** [comment]
Everything seems to be resolved here, reopen if I missed something.
