### ISSUE TITLE
dependency on `adm-zip` is breaking Linux CI servers

### ISSUE THREAD

**Issue by tehfoo** [bermi/sauce-connect-launcher#47]
This is maybe kind of a big deal.  Your dependency on `adm-zip` is picking up badly versioned code downstream.  Those authors have pushed changes that violate semver, and the result is Linux systems without proper build dependencies that run CI tests using this module are breaking.

See:
https://github.com/cthackers/adm-zip/issues/121
https://github.com/askovpen/node-fidonet-mailer-binkp-crypt/issues/8

As an improvement to this really handy project, I'd suggest moving off `adm-zip` and instead using the zlib support that's built into node?

http://nodejs.org/api/zlib.html

At the least don't blindly accept downstream updates from them?  They have obviously unreliable dependencies.

**Comment by tehfoo** [comment]
I should clarify, it seems like systems that don't have python available to build the downstream dependency will have a problem.  A quick workaround may be setting up npm-shrinkwrap with --dev flag and rolling back the breaking dependency to avoid the changes

**Comment by tehfoo** [comment]
FYI, adm-zip  fixed this [1], so we're no longer breaking.  But the advice to move to the node zlib still stands.

1: https://github.com/cthackers/adm-zip/commit/d8ed9063262309b700d0cfa1979d948aa3ac515c

**Comment by tehfoo** [comment]
Also closed the upstream issue: https://github.com/karma-runner/karma-sauce-launcher/issues/65

**Comment by aearly** [comment]
A PR to remove the dependency on `adm-zip` and simply use `zlib` directly would be welcome.  Looks like `adm-zip` has things sorted out for now.  I'm considering locking the dep to 0.4.7 so we don't get any more surprises in the future.
