### ISSUE TITLE
Feature request: use Npm download mecanism instead of Http request

### ISSUE THREAD

**Issue by jmorille** [bermi/sauce-connect-launcher#52]
Like discut in
- https://github.com/Polymer/wct-sauce/issues/5
- https://github.com/Polymer/web-component-tester/issues/140

Not use Http request to download plugins but use the npm registry mecanim by putting them in the heroku registry.

 That will permit to secure, cache and accelerate the installation procedure (thank to enterprise npm registry).

That permit to be used in company with Business Continuity Plan (BCP) constraint or behind a corporate firewall.

**Comment by bermi** [comment]
@jmorille Would this imply that we'd be on the hook for keeping a copy of SC on npm? Would it work for you to specify the path to sauce connect via an environment variable and skip the download process?

**Comment by sebv** [comment]
I guess it'll be best to get rid of the post-install trigger, and move it to a custom script. To do that using an environment variable is not great.

**Comment by jmorille** [comment]
sorry for my late response, I come back from vacancies...

I would like that the download mecanism use the npm configuration, in order to pass by me corporate proxy cache (Sonatype Nexus), with respect of NPM download convention, to have a local cache.
THe actual mecanism use a direct download, that don't pass the proxy configuration and not use the local Npm registry.

**Comment by sonnyking** [comment]
Yes, this issue is preventing a fortune 100 enterprise from adopting WCT, hundreds of developers.

**Comment by mdwragg** [comment]
@sonnyking :+1:

**Comment by Jonahss** [comment]
Ah I see. Sounds like a good thing to fix.

**Comment by panuhorsmalahti** [comment]
:+1:

**Comment by johanneswuerbach** [comment]
Closing as sauce-connect-launcher supports http proxies now: https://github.com/bermi/sauce-connect-launcher/pull/80
