### ISSUE TITLE
Share ownership of this repo with Sauce Labs

### ISSUE THREAD

**Issue by bermi** [bermi/sauce-connect-launcher#55]
Given @aearly  and I are not actively using Sauce Labs on our projects, it's becoming increasingly difficult to keep up with feature requests and bug requests.
These have been mostly related to changes and additions on the Sauce Connect jar, so we decided to get in touch with the team at Sauce Labs to check if they could also help out.

It looks like Sauce Labs is going to have some resources to help keeping this project in sync with sauce connect.

@sebv, @jlipps as discussed via email I'm happy to share ownership of this repo and the npm package with your team. Please send me the npm and github user names for the people that will be helping out.

**Comment by geekdave** [comment]
:+1:

**Comment by sebv** [comment]
You can add both of us our username are the same on npm or github.

**Comment by bermi** [comment]
You're all setup. Thanks for your help!
