### ISSUE TITLE
Question on Sauce connect proxy pac support.

### ISSUE THREAD

**Issue by Raghulraj** [bermi/sauce-connect-launcher#57]
Hi Bermi,

I would like to use proxy pac support in sauce launcher. Is it currently available? If not, can you please add this feature. Sauce supports --pac in command line.

 sc -u xxx -k xxx --pac xxx

Thanks,
Raghul

**Comment by aearly** [comment]
You  can pass `pac: "xxx"` in your options object and it will be converted to a CLI arg for sauce connect.

**Comment by Raghulraj** [comment]
I have tried it, but its not working. I am running it from corp network. tunnel session is created, but not able to access my qa env. Its working fine, when i run 'sc' command with --pac option from command line.

**Comment by sebv** [comment]
You should be able to see the command arguments in the log.

**Comment by sebv** [comment]
https://github.com/bermi/sauce-connect-launcher/blob/master/lib/sauce-connect-launcher.js#L273

**Comment by Raghulraj** [comment]
Sorry, its my bad. now its working. Thanks for the help.
