### ISSUE TITLE
Question: When will be the latest sauce connect add to the launcher?

### ISSUE THREAD

**Issue by raghulraj** [bermi/sauce-connect-launcher#63]
The latest sauce connect had a fix  that solves our connection issue to sauce. So I would like to know, when would be the latest [4.3.9 or 4.3.10] add to the launcher. 

Thanks,
Raghul

**Comment by Jonahss** [comment]
Right now! Thanks for asking. Pull Request #64 . Will publish to npm as soon as that's merged

**Comment by Jonahss** [comment]
published :)

**Comment by raghulraj** [comment]
Thanks :+1:  :)
