### ISSUE TITLE
Could we get a release?

### ISSUE THREAD

**Issue by johanneswuerbach** [bermi/sauce-connect-launcher#66]
https://github.com/bermi/sauce-connect-launcher/pull/60 looks like a nice addition, any chance to release that?

**Comment by jlipps** [comment]
@Jonahss have you released this before?

**Comment by geekdave** [comment]
:+1:

**Comment by lo1tuma** [comment]
:+1:

**Comment by Jonahss** [comment]
oh!
Let me see about publishing this right now.

**Comment by Jonahss** [comment]
published as 0.13.0 :)
