### ISSUE TITLE
Verify Sauce Connect checksums

### ISSUE THREAD

**Issue by johanneswuerbach** [bermi/sauce-connect-launcher#70]
Sauce is publishing Sauce Connect checksums. Those should be verified to prevent correct archives were downloaded.

**Comment by mehmetg** [comment]
Were are they published? The MD5 checksum is not part of the versions.json yet.

**Comment by johanneswuerbach** [comment]
Here: https://wiki.saucelabs.com/display/DOCS/Setting+Up+Sauce+Connect
