### ISSUE TITLE
Feature Request: Add option to use a provided path to sauce connect executable

### ISSUE THREAD

**Issue by azakus** [bermi/sauce-connect-launcher#75]
For users in restricted network environments, the automatic `downloadAndRun` functionality will fail to download sauce connect.
I understand the issues around using less-secure methods of downloading the proxy, but the current workarounds a bit of manual work: https://github.com/Polymer/wct-sauce/issues/5#issuecomment-164083574.

I'd like to propose a new option, `scPath`, that will run the `sc` file at the given path and reuse all the startup/teardown logic this module already provides. That way it is up to the user to provide the `sc` binary without sacrificing the security of procuring it from this module.

What do you think?

**Comment by johanneswuerbach** [comment]
You can find a WIP PR here https://github.com/bermi/sauce-connect-launcher/issues/75 :-)
