### ISSUE TITLE
Tunnel immediately shuts down

### ISSUE THREAD

**Issue by adjavaherian** [bermi/sauce-connect-launcher#77]
Not sure if I'm doing it right, but the tunnel appears to open properly and then immediately shuts itself down (cleanly).  How do I leave it open while I spawn karma tests?

**Comment by khirakawa** [comment]
I had the same issue, and I noticed that if I set `verbose` to `true`, the process persists...

**Comment by ayxos** [comment]
Check if the selenium port (4444/4445) is already in use.

**Comment by johanneswuerbach** [comment]
Closing as there hasn't been any further input. Please reopen when you still have this issue and more details.
